### PR TITLE
LPS-74258 Deactivating a site removes the users from the search for other sites as well

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74258](https://issues.liferay.com/browse/LPS-74258).<br><br>Hey Mike, this looks fine to me, but I want to run it by you since you know these components better. Hugo mentioned that this fix pertains to a customer issue.<br><br>/cc @ling-alan-huang, @hhuijser

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by samuelkong** [comment]
@mhan810 Can you help review this. This is for a customer ticket. Thanks.

**Comment by mhan810** [comment]
@drewbrokke please fwd to BC.  This looks good

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/51710.

**Pull request closed without merging**
