### PR TITLE
LPS-52177 Company Deletion

### PR DESCRIPTION
**Pull request by arbetts**
@mhan810,

I think the CI is down at the moment so I made the change i think is necessary to update the package info, but i'm very unfamiliar with this.

Sending back to you to see if 1) the CI will work, 2) check if i missed any other packages. 

From what i could tell, I only needed to update the one package file.

i found 568f915d as a reference

if the CI wasn't down i would have forwarded to BChan

### CODE REVIEW

**Comment by arbetts** [comment]
well that definitely wasn't the only file i needed to change.

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
@mhan810 I don't think the new versions of the package are being made available. I'll look into this tomorrow if you don't already know how to get the CI to recognize the package changes

**Comment by mhan810** [comment]
@arbetts I'm splitting the search commits out to another LPS.  Let's see if that'll make it easier...

**Comment by arbetts** [comment]
@mhan810 sounds good.
do you want me to rebase changes and resend after the other LPS is committed?

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/38236 ok resent aagain.

@arbetts yes please rebase once the pull goes in

**Comment by arbetts** [comment]
@mhan810 

rebasing and will resend

**Comment by arbetts** [comment]
https://github.com/mhan810/liferay-portal/pull/1156

**Pull request closed without merging**
