### PR TITLE
LPS-70234 Kaleo/workflow classloader has not access to scripting engine

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
Hi @mhan810,

Answering your previous comment in #1302, sorry, that was my bad, I should not have included the dynamic imports in that unrelated module due to the reason you have pointed out. Unfortunately, I had done some previous testing and I forgot to remove that line when I sent that PR.

After removing it the fix is still fully functional. Can you see anything else that may be problematic in this fix?

I am not very on this strategy of having to change the CCL but as far as I can see I do not find any other fix that does not imply more modifications. Executors, such as the GroovyExecutor, receive an AggregateClassloader of two classloaders (the GroovyExecutor classloader and the CCL which is a ContextFinder pointing to the Framework Bundle Classloader) but none of them is the kaleo-runtime-scripting-impl's classloader. Switching the CCL to the kaleo-runtime-scripting-impl's classloader does the trick.

I have completed this fix by applying the CCL-modification strategy to the rest of the evaluators/executors contained in this module but I did not touch DRL*Executors or DRL*Evaluators because they should not be affected by this, should they?

Thanks in advance

**Comment by mhan810** [comment]
@dacousalr I was a bit surpirsed by the need to use the CCL.  I was actually expecting the CCL to be the classloader of the module already.  When you were debugging, what classloader did you see in the scripting module?  Was it the classloader of the kaleo-script module or a different module?

**Comment by dacousalr** [comment]
@mhan810 None of them. What I could read is something like `org.eclipse.osgi.internal.framework.ContextFinder@60f4928d`
The currentThread is `Thread[liferay/kaleo_graph_walker-2,5,main]`

if I take look at its attribute "classes", it shows: `[class com.sun.proxy.$Proxy386]` 
Its parent is `com.liferay.portal.module.framework.ModuleFrameworkClassLoader@4218f921`
and the parentContextClassLoader is also `com.liferay.portal.module.framework.ModuleFrameworkClassLoader@4218f921`

**Comment by mhan810** [comment]
@dacousalr ah I see, right, because the thread is from the graph walker module.  Understood, then we need to swap classloaders.  I'll merge

**Comment by dacousalr** [comment]
Thank you very much, @mhan810

**Comment by mhan810** [comment]
Centralized more logic in pr to BC: https://github.com/brianchandotcom/liferay-portal/pull/46566

**Pull request closed without merging**
