### PR TITLE
LPS-73586 Add highlight portlet configs and remove highlight property

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:retest

**Comment by BryanEngler** [comment]
Hey Mike, there are changes to the journal repo that go with this, https://github.com/BryanEngler/com-liferay-journal/pull/1, do you want someone else to review the journal changes?

**Comment by mhan810** [comment]
@BryanEngler can you send those to @ealonso and copy me?

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:retest

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/50427

@BryanEngler good job, minor change in https://github.com/brianchandotcom/liferay-portal/pull/50427/commits/68e45e2efb81fa72e6dac1b1ff049fba278b3fd3

**Pull request closed without merging**
