### PR TITLE
LPS-52177

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by mhan810** [comment]
@arbetts do you really need: https://github.com/mhan810/liferay-portal/pull/1156/commits/12d3a3fb6a077f19df766358facc026bf87667ae?  I think that's not necessary right, especially since we are not indexing if company is in deletion mode

**Comment by arbetts** [comment]
@mhan810 

right ... that commit is not needed ... i thought i had removed that one when i rebased, but i guess not.

i'll update the pull

**Comment by arbetts** [comment]
@mhan810 pr updated to remove 12d3a3f

did a basic test by adding and removing a company and there were no index errors

**Comment by arbetts** [comment]
ci:retest

**Comment by mhan810** [comment]
test failures...

https://github.com/arbetts/liferay-portal/pull/58

**Pull request closed without merging**
