### PR TITLE
LPS-65121 Redeploy of com.liferay.portal.search makes Search unusable

### PR DESCRIPTION
**Pull request by arboliveira**
Hi @mhan810, @rotty3000,

These fixes make it possible to redeploy `com.liferay.portal.search.jar` several times (delete then undelete); interspersed with redeploys switching between Elasticsearch and Solr in the same session, without restarting Portal; and search functionality staying operational all the way through.

However, some odd things I observed:

**(1)**

After the first redeploy of `com.liferay.portal.search.jar`, this shows up in the console:

```
19:39:14,684 ERROR
[fileinstall-/Users/arbo/Liferay/bundles/liferay-portal/osgi/portal]
[com_liferay_calendar_service:97]
[com.liferay.calendar.search.CalendarIndexer(2116)]
Circular reference detected, getService returning null
```

I'd think this happens because `CalendarIndexer` (an `Indexer`) has a `Reference` to `IndexerRegistry` at the same time `IndexerRegistryImpl` (the `IndexerRegistry`) has a `Reference` to `Indexer`. I just can't tell why this error doesn't show up on container startup, only on redeploy. Should @brandizzi be worried?

**(2)**

After the _second_ redeploy of `com.liferay.portal.search.jar`, this _also_ shows up in the console:

```
19:39:13,953 ERROR
[fileinstall-/Users/arbo/Liferay/bundles/liferay-portal/osgi/portal]
[com_liferay_portal_search_elasticsearch:97]
[com.liferay.portal.search.elasticsearch.internal.ElasticsearchEngineConfigurator(2984)]
Circular reference detected, getService returning null
```

In this fix, I did indeed change `ElasticsearchEngineConfigurator` to be injected a `Reference` to `SearchEngineHelper`, while `SearchEngineHelperImpl` already had a `Reference` to `SearchEngineConfigurator`. It was necessary to inject at the module level because formerly the logic relied on `AbstractSearchEngineConfigurator` invoking `SearchEngineHelperUtil` which holds a `ProxyFactory.newServiceTrackedInstance(SearchEngineHelper.class)` -- problem is, this proxy returns `null` on redeploys and breaks `ElasticsearchEngineConfigurator`. Injecting by `Reference` makes search work perfectly across redeploys, but we're left with the (legitimate) warning. Should we be worried? Should I try and split a third `Component` in order to break the circular reference?

**(3)**

After ten or twelve redeploys in the same Portal session (`com.liferay.portal.search.jar`, `com.liferay.portal.search.elasticsearch.jar`, `com.liferay.portal.search.solr.jar`) with minimal search and reindex activity, I get:

```
java.lang.OutOfMemoryError: PermGen space
```

This, together with the evidence collected from https://github.com/brianchandotcom/liferay-portal/pull/38879 (context classloader was the old bundle classloader from before redeploy, instead of the new bundle classloader) makes me wonder... could redeploy of bundles be retaining classloaders?

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by mhan810** [comment]
@arboliveira hey this looks good, go ahead and send to Brian

**Pull request closed without merging**
