### PR TITLE
Search partial update permission test 21

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @mhan810,

Here is the latest development for Fast Permission Indexing.
Can you help take a look and see if you think our current approach would work? 

Currently, our new approach overcomes two main issues:

- Make BaseModelRetriever work for all types of assets
- Make sure the Document generated for the partial update is updating the correct index and fields

The following section will provide more in-depth details about the main issues this pr tries to resolve.

Please let me know if you have any questions.
Thanks!

----

## Make BaseModelRetriever work for all types of assets

We are currently running into this issue when trying to retrieve a baseModel for **JournalArticle**.

The primKey that is used is actually taken from **JournalArticleResource**
**Source:** [JournalArticleLocalServiceImpl.java#L737-L740](https://github.com/ericyanLr/liferay-portal/blob/search-partial-update-permission-test-21/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L737-L740)

Our current solution is to utilize **AssetRendererFactory** to properly retrieve the baseModel.
**Commit:** https://github.com/ericyanLr/liferay-portal/pull/61/commits/11f8968159b427983ce0d961dbb4ddf5a9e92de2

## Make sure the Document generated for the partial update is updating the correct index and fields

We are currently running into this issue when trying to generate the proper partial-update document for **JournalArticle**.

It looks like the **JournalArticleIndexer** modifies the **UID** field and overwrites the **UID** field that was initially set from the **BaseModelDocument**.
**Source:** [JournalArticleIndexer.java#L495-L503](https://github.com/ericyanLr/liferay-portal/blob/search-partial-update-permission-test-21/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/internal/search/JournalArticleIndexer.java#L495-L503)

Our current solution is to utilize the associated **Indexer** itself to retrieve a document that represents our baseModel. We would then use the retrieved document to **populate the necessary fields** on a newly generated **document for our partial-update**.
**Commit:** https://github.com/liferay/liferay-portal/commit/bbc3f427697303f338c39e1a7aac1ef54d1d6dc3

**Note:** We also added changes to allow for fields to use **null** as a value
This was needed to do partial-updates on fields that are expected to be **empty**

From my understanding, this should also work with the New Indexers, but I haven't actually tested that yet.

### Another example for: Document generated for the partial update
We noticed that when adding permission fields, **Field.RELATED_ENTRY** is used to make certain decisions on permission fields. 
**Source:** [SearchPermissionDocumentContributorImpl.java#L63-L73](https://github.com/ericyanLr/liferay-portal/blob/search-partial-update-permission-test-21/modules/apps/foundation/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/permission/SearchPermissionDocumentContributorImpl.java#L63-L73)

This field, and it's associated fields, are actually not included in the **BaseModelDocument**.

Our current solution ensures that **Field.RELATED_ENTRY** and it's associated fields are also included in the document.
**Commit:** https://github.com/ericyanLr/liferay-portal/pull/61/commits/bbc3f427697303f338c39e1a7aac1ef54d1d6dc3#diff-7c50c822511363dfd5e08926aafc7586R88

**Example of usage:** [DLFileEntryIndexer.java#L512-L535](https://github.com/ericyanLr/liferay-portal/blob/search-partial-update-permission-test-21/portal-impl/src/com/liferay/portlet/documentlibrary/util/DLFileEntryIndexer.java#L512-L535)

## CI Tests
The new changes are passing our newly added test and do not appear to be breaking any existing tests. **Ci Test Results:** https://github.com/ericyanLr/liferay-portal/pull/61

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @mhan810, 
Just added an additional commit to the branch, minor fix for a comparison.

**Comment by ericyanLr** [comment]
Hi @mhan810,

I was wondering if you had a chance to take a look at this pr.
Thanks!

**Comment by mhan810** [comment]
@ericyanLr hey, I haven't had time yet, will look tonight and poke my head upstairs tomorrow

**Comment by ericyanLr** [comment]
Sounds good, thanks for the update!

**Comment by mhan810** [comment]
closing pending changes discussed w/ eric offline

**Pull request closed without merging**
