### PR TITLE
LPS-58444 (+LPS-58832) - Extract portal-setting-web authentication/cas.jsp  into portal-security-sso-cas

### PR DESCRIPTION
**Pull request by topolik**
Hi Mike,

I managed to pull cas.jsp the right way => portal-security-sso-cas is hooking into portal-settings-web module, not the other way.

And it should be extensible for other modules as well.

For that I had to modify in **portal core**:
1, `MVCPortlet`: extend `MVCActionCommand` with `FormMVCActionCommand` to support validation phase and after then the action phase - this also fixes https://issues.liferay.com/browse/LPS-58832
2, `MVCPortlet`: extend multiple `MVCActionCommand` support and use `String[] request.getParameterValues("javax.portlet.action")` to parse all parameters with the same name from the request
3, `ParameterMapSettings`: parse also our `cas--` parameters from request when validation fails
4, Localization trackers to support full resource bundle registrations, this feature seems half-baked

Then I went and modified **portal-settings-web** module:
1, added extension point so that `DynamicInclude` can specify `tab-name` property which will be used in the `authentication.jsp`, if there (in portal-settings) wouldn't be the tabs only common DynamicInclude would be fine :(
2, moved localization keys and `cas.jsp` into portal-security-sso-cas module
3, changed `EditCompanyMVCActionCommand` to support separate validation via `FormMVCActionCommand`

Then inside **portal-security-sso-cas** module
1, Adapted cas.jsp to read configuration from CASConfiguration and/or request (using ParameterMapSettings) when validation fails ... this required to use the `cas--` prefix for parameter names
2, hooked `cas.jsp` into portal-settings-web using the dynamic include implementation (`PortalSettingsCASAuthenticationDynamicInclude`)
3, implemented `PortalSettingsCASAuthenticationFormMVCActionCommand` to validate the input and then save the configuration
4, Registered `cas.jsp` localization to be used from portal-settings-web using `PortalSettingsPortletResourceBundlePublisher`

Thanks!

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
cc @philipjones03

**Comment by topolik** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
I restarted this job on 10/15/15 at 12:17pm.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/31140

**Pull request closed without merging**
