### PR TITLE
[TS] LPS-78277 - When log off from Liferay, "ArrayIndexOutOfBoundsExceptio…

### PR DESCRIPTION
**Pull request by hhuijser**
…n" will be occurred, if "Token Based SSO" enable with using "Logout Redirect URL".

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by mhan810** [comment]
@hhuijer go ahead and send to vrian

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by mhan810** [comment]
@daviddotzhang go ahead and send to Brian Chan

**Comment by daviddotzhang** [comment]
@mhan810 got it, thanks.

**Comment by daviddotzhang** [comment]
@hhuijser  I have sent it here https://github.com/brianchandotcom/liferay-portal/pull/55773

**Comment by lipusz** [comment]
Closing as it has already been fixed. :+1:

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
