### PR TITLE
LPS-68565

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey Mike,

I was told by Minhchau that you gave the go-ahead to add the missing LDAP properties to the Instance Settings screen. Let me know if you see any issues with this implementation or want me to change anything.

/cc @jorgeferrer

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@mhan810 Not sure about the version changes, so let me know if there's anything else needed for that.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/43763

@jonathanmccann 

(1) for the build.gradle, you should not use "default" see my changes in: https://github.com/brianchandotcom/liferay-portal/pull/43763/commits/59f837180346b59916aa6ac58926859fcff5bb56

(2) I opted to move the constants used strictly in by the ldap.jsp to the web package to avoid impl specific dependencies.

**Pull request closed without merging**
