### PR TITLE
LPS-64961

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This issue is caused by LPS-61083:
  - https://github.com/brianchandotcom/liferay-portal/pull/33061/commits/6f8c5a2671c8c38dfb709981071507a900800532

We are creating a new "NoAutoCommitIndexer" object for each IndexRequest, so *IndexerRequest.equals* always returns false because {{(Validator.equals(_indexer, indexerRequest._indexer)}} is always false

I am adding a equals method to NoAutoCommitIndexer and compare its internal indexer

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

On Friday, April 8, 2016, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 1 hour 9 minutes 1 second
> Base Branch:
>
> Branch Name: master
> <https://github.com/liferay/liferay-portal/tree/master>
> Branch GIT ID: ed7b69f5b0cda2473ed7777d77abf410c4d25348
> <https://github.com/liferay/liferay-portal/commit/ed7b69f5b0cda2473ed7777d77abf410c4d25348>
> Job Summary:
>
>    - *test-portal-acceptance-pullrequest(master)
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/1/>*
>    - test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk7
>    <https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-hypersonic20-jdk7/0
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/0
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/1
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/10
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/330/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/11
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/354/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/12
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/378/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/13
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/14
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1365/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/15
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/379/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/16
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/355/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/17
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/720/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/18
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/332/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/19
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/330/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/2
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/20
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/777/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/21
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/22
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/23
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/24
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/778/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/25
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/332/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/26
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/721/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/27
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/338/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/28
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/334/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/29
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/722/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/3
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/30
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/31
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/32
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/33
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/34
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/35
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/36
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/4
>    <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1350/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/5
>    <https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/729/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/6
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/7
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/702/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/8
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/329/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/9
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1364/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-postgresql94-jdk8/0
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-wildfly10-mariadb100-jdk8/0
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4/>
>    - *test-portal-acceptance-pullrequest-batch(master)/integration-hypersonic20-jdk7
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339/>*
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-mysql56-jdk7
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/335/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-postgresql94-jdk7
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic20-jdk7
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/340/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql56-jdk7
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql94-jdk7
>    <https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/330/>
>    - test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk7
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/780/>
>    - test-portal-acceptance-pullrequest-batch(master)/plugins-compile-jdk7
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/381/>
>    - test-portal-acceptance-pullrequest-batch(master)/portal-web-jdk7
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/724/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/ruby-sass-compiler-jdk7
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/6/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk7
>    <https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/382/>
>    - test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk7
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7/>
>    - test-portal-acceptance-pullrequest-batch(master)/tck-jdk7
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/336/>
>    - test-portal-acceptance-pullrequest-batch(master)/unit-jdk7
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8/>
>    - test-portal-acceptance-pullrequest-source(master)
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/1/>
>
> For more details click here
> <https://test-1-18.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1/jenkins-report.html>
> .
> ------------------------------
> Failed Jobs:
>
>    1. test-portal-acceptance-pullrequest(master)
>    <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/1/> Job
>    Results:
>
>    55 Jobs Passed.
>    2 Jobs Failed.
>
>    Completed with the status of FAILURE.
>
>    2.
>    test-portal-acceptance-pullrequest-batch(master)/integration-hypersonic20-jdk7
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339/> Job
>    Results:
>
>    5777 Tests Passed.
>    1 Test Failed.
>    1. MBMessageServiceTest.testAddMessagesConcurrently
>       <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/339//testReport/com.liferay.portlet.messageboards.service/MBMessageServiceTest/testAddMessagesConcurrently>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mhan810/liferay-portal/pull/1163#issuecomment-207559963>
>


-- 

Jorge Díaz Estebaranz

Engineer, Technical Support

Subscription Services | Spain and Portugal

Liferay Spain
Liferay Enterprise. Open Source. For Life.

Visit Us: www.liferay.com | Like Us: facebook.com/liferay | Follow Us:
twitter.com/liferay

*Aviso de Confidencialidad: **Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.*
*Confidentiality Notice: **This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message.
Thank you.*

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/38716

**Pull request closed without merging**
