### PR TITLE
DDMFields type text created as Indexable-Text are indexed as Keyword

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
Some considerations to this PR:

1) As it was recommended in https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/16135494, indexable-text fields begin with ddm__text and indexable-keyword fields begin with ddm__keyword.
2) Finally, it was enough to add a mapping only for ddm__keyword case to configure it for the keyword analyzer. ddm__text fields are matched by the existing locale regular expressions *_ar, *_es_ES, *_en_US, etc picking up its correspondent language analyzer.
3) In JournalArticleIndexer there is a distinction between the code for ElasticSearch and the code for Solr because Elasticsearch accepts the string value as is but Solr and Lucene need to receive it between quotes in order to work in the same way, especially if the string value contains spaces.

**Comment by mhan810** [comment]
@dacousalr can you check the failed tests?

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
I have sent you an updated PR (https://github.com/mhan810/liferay-portal/pull/749).

I close this.

**Pull request closed without merging**
