### PR TITLE
[TS] LPS-70504 NullPointerException when exporting assigning a User to a User Group when LDAP export is enabled

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-70054

Hi Mike,

Even though the NPE is caused by misconfiguration, I think the real exception should appear in the log for the better understanding.

Regards,
Tibor

Autor: @rodrigopaulino
Reviewers: @cleydyr, @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Updated to latest HEAD.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/47184

**Pull request closed without merging**
