### PR TITLE
 LPS-62665 Add prefix to index name to avoid some problems 

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by mhan810** [comment]
@jorgediaz-lr hey Jorge, I put together a slightly diff way.  See: https://github.com/mhan810/liferay-portal/pull/1031

**Comment by jorgediaz-lr** [comment]
Hi @mhan810 your code looks good. Thank you!

**Pull request closed without merging**
