### PR TITLE
LPS-64210

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @mhan810 

I am adding some debug traces to IndexerRequestBuffer functionality as they are necessary for Support people during problems diagnose

(I was testing Staging activation at master and I need them in order to check IndexerRequestBuffer requests during publish operation)

https://issues.liferay.com/browse/LPS-64210

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Rebased to last master

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/38096

@jorgediaz-lr I reverted your reordering of the toString since BC normally wants these in alphabetical for consistency

**Pull request closed without merging**
