### PR TITLE
LPS-61440

### PR DESCRIPTION
**Pull request by briangreenwald**
Restructured commits

### CODE REVIEW

**Comment by briangreenwald** [comment]
Updating these to use the new abstract class. Will resend when finished

**Comment by mhan810** [comment]
Hey I have a branch with the code already but was failing tests.  Let me
send

Sent from my mobile device.

**Comment by briangreenwald** [comment]
One thing I just noticed was that in TokenConfiguration, we have something called authenticationCookies() but there doesn't appear to be a corresponding legacy property setting for either SiteMinder or Shibboleth. The error wasn't showing up prior to the addition to the abstract class because my implementation of storeSettings was slightly different. How should this property be treated if it's not a legacy setting?

**Comment by mhan810** [comment]
It's a new setting so no need to migrate it

**Comment by briangreenwald** [comment]
Gotcha. So I guess my last question would be how you would handle the call in storeSettings since it calls settingsDescriptor.getAllKeys(), which in turn includes the new setting. In BaseCompanySettingsVerifyProcess, it'll call dictionary.get(...) which will return null for this setting, thus prompting a NPE when it calls .equals on it a few lines down on 78. This problem didn't materialize for my original implementation (where I had to implement the method on my own) because instead of dictionary.get(...), I used GetterUtil.getString(dictionary.get(name)) which gives you an empty string in the event of a null value.

**Comment by mhan810** [comment]
Got it, let's change the base class to use GetterUtil

**Pull request closed without merging**
