### PR TITLE
[TECHNICAL SUPPORT] LPS-60527 Version qualifier (e.g. SNAPSHOT) is not displayed in the App Manager

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-60527

Hi Mike,

Hopefully you can review this a I couldn't find a better person based on the Cross-Functional Teams wiki and the component hierarchy sheet. :-)

Originally, Ádám wanted to consider the qualifier when we compare 2 versions, though, we cannot do this without having a list of supported qualifiers and the hierarchy between them.

So I wrote him this:

>1- SNAPHOT is a special qualifier used mainly in MAVEN projects and is usually related to continuous integration. Here's a good article: https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm

>2- Using alpha-numerical characters are allowed, though, discouraged by https://www.liferay.com/documentation/liferay-portal/6.2/development/-/ai/marketplace-basics-liferay-portal-6-2-dev-guide-11-en ("Version" section).
Without a hierarchy, neither the portal nor humans can decide the relationship between two versions.

>3- There can be other qualifiers, e.f. NIGHTLY, BETA etc. The proposed solution doesn't preserve such qualifiers.

>What I'd do is to keep the qualifiers in when constructing the toString from a Version, but doesn't use it when comparing versions. I am not aware of any documentation saying Liferay is tied to the MAVEN versioning, so the comparison should not deal with these special cases in my opinion.

And now the solution is ready and I'm forwarding it to you.

**Note**
On Master there is an issue, so the App Manager portlet cannot be opened, therefore nothing can be seen. See: LPS-60766. We used a former HEAD to reproduce the issue and test the solution: @d30b7827cb7b4abc7239aaf790ae6e83831753cf

Let us know if you have any concerns.

Thanks,
Tibor

/cc @adamnagy

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
SF error looks unrelated to our changes.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest HEAD.

@mhan810: Please, let me know if I should forward it to someone else.

Thank you in advance,
Tibor

**Comment by mhan810** [comment]
Will look today

Sent from my mobile device.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by mhan810** [comment]
https://github.com/JorgeFerrer/liferay-portal/pull/617

**Pull request closed without merging**
