### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @mhan810 

Looks like you wrote pretty much all the *.groovy stuff.
You mind having a look at my changes to *.groovy to make sure I am not messing up anything?

Go ahead and push to Brian if it looks okay

**Comment by mhan810** [comment]
ci:retest

**Comment by hhuijser** [comment]
@mhan810 

Okay to push this to Brian?

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:retest

**Comment by mhan810** [comment]
Sorry @hhuijser was out a few days last week.  Will review this today

**Comment by hhuijser** [comment]
No worries... just checking :)

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/38236

**Pull request closed without merging**
