### PR TITLE
LPS-72691 portal-search-web: folder facet without terms to display is not rendered.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test

**Comment by brandizzi** [comment]
ci:reopen

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/56828

**Pull request closed without merging**
