### PR TITLE
[TECHNICAL-SUPPORT] LPS-69669

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ericyanLr

### CODE REVIEW

**Comment by mhan810** [comment]
@jonathanmccann go ahead and send to master this is good to go.

btw i'm out of office for next couple weeks so push to @shuyangzhou please

**Comment by jonathanmccann** [comment]
Will do, thanks.

https://github.com/brianchandotcom/liferay-portal/pull/45524

**Comment by shuyangzhou** [comment]
@tomwang2011 run a performance regression on this. It should be fine, just want to be safe.

**Comment by tomwang2011** [comment]
@shuyangzhou Tested and this pull is safe, the difference between this and the baseline is less than 1%.

**Comment by shuyangzhou** [comment]
Thanks @tomwang2011 !

**Pull request closed without merging**
