### PR TITLE
LPS-57999 Avoid NPE

### PR DESCRIPTION
**Pull request by jkappler**
Hi @mhan810, would it make sense to add a check for null value here?

### CODE REVIEW

**Comment by jkappler** [comment]
Seems there was another PR for this, sorry

**Comment by jkappler** [comment]
But it was not commited

**Comment by mhan810** [comment]
sry was on vacation...

https://github.com/brianchandotcom/liferay-portal/pull/30124

**Comment by jkappler** [comment]
Sorry @mhan810, didn't know...

**Pull request closed without merging**
