### PR TITLE
LPS-60086 format-source

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @mhan810 this is the code for making sure that all jars and wars just get copied over to /osgi/modules  by default except for those wars that explicitly set "wab=false" in the liferay-plugin-package.properties those will be processed traditionally.

**Comment by mhan810** [comment]
K, ping when u get a chance and we can talk thru it on Mon.



*From:* Gregory Amerson [mailto:notifications@github.com]
*Sent:* Friday, January 8, 2016 1:13 PM
*To:* mhan810/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] LPS-60086 format-source (#922)



hey @mhan810 <https://github.com/mhan810> this is the code for making sure
that all jars and wars just get copied over to /osgi/modules by default
except for those wars that explicitly set "wab=false" in the
liferay-plugin-package.properties those will be processed traditionally.

—
Reply to this email directly or view it on GitHub
<https://github.com/mhan810/liferay-portal/pull/922#issuecomment-170096497>.

**Comment by mhan810** [comment]
@gamerson @migue is working on this one to completely remove as opposed to diverting.  Going to close this one out.

**Comment by gamerson** [comment]
Happy to hear where things are headed, good luck @migue

On Thu, Feb 4, 2016 at 1:28 PM, Michael Han <notifications@github.com>
wrote:

> Closed #922 <https://github.com/mhan810/liferay-portal/pull/922>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mhan810/liferay-portal/pull/922#event-539679290>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
