### PR TITLE
[TECHNICAL-SUPPORT] LPS-58506

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by mhan810** [comment]
@arbetts is there a reason we don't want to use the same analyzer at index time and search time?  It's very rare to use 2 different analyzers

**Comment by arbetts** [comment]
we want to use two different analyzers because we want to keep the behavior of matching a partial search on a tag, but we do not want to tokenize the results of the query.

say we have two WC articles

WC 1 has "red tag"
WC 2 has "blue tag"

if we use the same analyzer that does not tokenize the tag name, searching for "red" yields no results.

if we use the same analyzer that does tokenize the tag name, searching for "WC" will display the following hits: "red" 1, "tag" 2, "blue" 1.

only if we use two different analyzers do we get the desired behavior of a partial match search while displaying the right facets.

**Comment by mhan810** [comment]
understood the requirement. Ok, go ahead and send to BC.  The code is fine.

**Comment by jonathanmccann** [comment]
Sent - https://github.com/brianchandotcom/liferay-portal/pull/30131

**Pull request closed without merging**
