### PR TITLE
LPS-52177 simplify user deletion

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey Mike, I took a first look and it seemed fine but I know you mentioned some scalability problems, so you might want to look into this

### CODE REVIEW

**Comment by mhan810** [comment]
@arbetts @JorgeFerrer so my argument around company deletion is why do we even care to push it thru all the services?  Why can't we can do a mass delete?  We have added companyId to all tables.  So instead of calling the services, why don't we just do a delete from Foo where companyId = 1234?

Also, for Indexing, we don't need to index while we delete.  We already delete the search indices for a company when it's deleted via:

	protected void unregisterCompany(Company company) {
		PortalInstanceLifecycleManager portalInstanceLifecycleManager =
			_serviceTracker.getService();

		if (portalInstanceLifecycleManager != null) {
			portalInstanceLifecycleManager.unregisterCompany(company);
		}
	}

Specifically: SearchIndexPortalInstanceLifecycleListener

**Comment by JorgeFerrer** [comment]
Ok, so what do you want to do with this pull?

We can't change the whole implementation of deleteCompany to that strategy so late, right

**Comment by arbetts** [comment]
@JorgeFerrer @mhan810 

I agree that using the companyId is better in theory, (and in the long run it is better in practice too) but I looked into doing that first since Drew mentioned it. With our current framework, there is no way that i know of that grabs all of the models at runtime, and the persistedModelService does not have methods to delete by companyId. So the only way we can actually accomplish deleting all tables by companyId right now is to manually write all the sql and put that in the deleteCompany service method.

if you think this is better, I can go for it, but i didn't want to introduce an entirely new way to delete a model from our DB.

also, not all tables have a companyId (though almost all of them do). And I do not know if we can cancel any quartz jobs by companyId. Currently we unschedule staging tasks when deleting a group.

for your reference... the logic that was used beforehand is the following:
https://gist.github.com/arbetts/c09ccd39511448ebff1c

**Comment by mhan810** [comment]
OK let's do this: stop indexing for the company, delete and then let the
life cycle listener take care of deleting the company.

You'll need to add a setReadOnly(companyId) method to IndexWriterHelper?
Can't remember the interface

Sent from my mobile device.

**Comment by mhan810** [comment]
I'll take a run @ it and send it back to you @arbetts

**Comment by mhan810** [comment]
see https://github.com/arbetts/liferay-portal/pull/51

**Pull request closed without merging**
