### PR TITLE
LPS-62508 Newly created Portal Instances not indexing anything

### PR DESCRIPTION
**Pull request by arboliveira**
Hey Mike, this fixes:

https://issues.liferay.com/browse/LPS-62508
https://issues.liferay.com/browse/LPS-62510
https://issues.liferay.com/browse/LPS-62513

Can you take a look and see if this approach would be alright?

I've tested on a running Portal but haven't rebased yet on latest master post Tomcat 8; sent the code anyway just so you can read it. If you think this solution would be ok to go, I'll rebase and resend so you can do the review proper. 

cc @arturbr

### CODE REVIEW

**Comment by mhan810** [comment]
Hey I think this is OK, but might be better if we did in the checkCompany
method and call it preregisterPortalInstance or something like that?

**Comment by arboliveira** [comment]
Done.

Following existing naming style, renamed methods to `preregisterCompany` and `preregisterPortalInstance`.

https://github.com/arboliveira/liferay-portal/commit/93f9f077703458eaa9d72e7cd7702ab5929b3187 is the "light" version: invokes `SearchEngineHelperUtil` directly from `CompanyLocalServiceImpl` and does not change `PortalInstanceLifecycleListener`.

https://github.com/arboliveira/liferay-portal/commit/536f5c0281ecb1666d5cd2c03730b0814b0eedff is the "full" version, first proposed: changes `PortalInstanceLifecycleListener` and moves the `SearchEngineHelperUtil` call to be invoked from `SearchIndexPortalInstanceLifecycleListener`. This way, `CompanyLocalServiceImpl` remains uncoupled from Search infrastructure.

If you prefer the "light" approach, just drop the last commit :smiley:

**Comment by mhan810** [comment]
K I’ll take a look @ this branch.



-m



*From:* André de Oliveira [mailto:notifications@github.com]
*Sent:* Monday, February 1, 2016 11:08 AM
*To:* mhan810/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] LPS-62508 Newly created Portal Instances
not indexing anything (#1004)



Done.

Following existing naming style, renamed methods to preregisterCompany and
preregisterPortalInstance.

arboliveira@93f9f07
<https://github.com/arboliveira/liferay-portal/commit/93f9f077703458eaa9d72e7cd7702ab5929b3187>
is the "light" version: invokes SearchEngineHelperUtil directly from
CompanyLocalServiceImpl and does not change PortalInstanceLifecycleListener.

arboliveira@536f5c0
<https://github.com/arboliveira/liferay-portal/commit/536f5c0281ecb1666d5cd2c03730b0814b0eedff>
is the "full" version, first proposed: changes
PortalInstanceLifecycleListener and moves the SearchEngineHelperUtil call
to be invoked from SearchIndexPortalInstanceLifecycleListener. This way,
CompanyLocalServiceImpl remains uncoupled from Search infrastructure.

If you prefer the "light" approach, just drop the last commit [image:
:smiley:]

—
Reply to this email directly or view it on GitHub
<https://github.com/mhan810/liferay-portal/pull/1004#issuecomment-178072034>
.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/35324

**Pull request closed without merging**
