### PR TITLE
LPS-54638

### PR DESCRIPTION
**Pull request by holatuwol**
Please see: https://issues.liferay.com/browse/LPS-54638

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by mhan810** [comment]
see changes in pr to BC.

https://github.com/brianchandotcom/liferay-portal/pull/26305

**Pull request closed without merging**
