### PR TITLE
LPS-66462

### PR DESCRIPTION
**Pull request by arbetts**
removing the background tasks for this seems like the right approach. Notifying subscribers doesn't need to be persisted or displayed to the end user.

I don't know if sending in bulk (i.e. subscriptionSender.setBulk(true); ) is better, but this looks like a good change to me.

cc @ealonso @Preston-Crary

### CODE REVIEW

**Comment by ealonso** [comment]
@juliocamarero @pavel-savinov

**Comment by pavel-savinov** [comment]
Hey @Preston-Crary, please take in account that we also should notify subscribers when some asset was added to the asset publisher's selection in the **manual** mode. That was the purpose of the code you deleted in 8653c71da70381e04f3fac7c741d2508fb5eabf8 and that is why we need a background task there(because it can take a long time to notify all the subscribers).

**Comment by mhan810** [comment]
@arbetts can you send to @pavel-savinov and @juliocamarero on WEM team first?  I can look at the background task stuff after

**Comment by arbetts** [comment]
@mhan810 will resend to @pavel-savinov and @juliocamarero 

@pavel-savinov @juliocamarero we should not use a background task unless there is a compelling reason. we can write a message listener and send a message across the messageBus. this will accomplish the intended behavior without adding all of the extra overhead of a background task.

**Comment by Preston-Crary** [comment]
@pavel-savinov Yes we need to notify them, but we already have CheckAssetEntryMessageListener that runs a job every 24 hours and sends out notifications for anything that hasn't already had a notification sent out.  The idea behind 8653c71 is to leave this task to that job instead of creating and performing these tasks as they happen.

**Comment by Preston-Crary** [comment]
Please see https://github.com/juliocamarero/liferay-portal/pull/4183

**Pull request closed without merging**
