### PR TITLE
LPS-90255 Convert each Instance Settings entry to match System Settings' information architecture

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-90255](https://issues.liferay.com/browse/LPS-90255).<br><br>Hey Mike, this is a first draft at converting the PortalSettingsFormContributor entries to render ConfigurationScreen entries in the new Instance Settings.  The backend actions on form submit don't change, only where the jsps are rendere.  So in this example, NTLM and CAS will now each be their own entries in the SSO category.  Please let me know what you think.  I'm out for the day so we can talk tomorrow if you'd like.

### CODE REVIEW

**Comment by drewbrokke** [comment]
If this pattern looks good, I'll apply it each usage of PortalSettingsFormContributor.

cc @dejuknow

**Comment by mhan810** [comment]
@drewbrokke do we have the UX mockups this is supposed to match or do I need to build this puppy?

**Comment by drewbrokke** [comment]
Sorry I’ll try to send screens a little later tonight or tomorrow morning

**Comment by drewbrokke** [comment]
@mhan810 I'm going to close this to update a few things so that the UI matches the design more closely.  Here are the two design links I'm working from: [CAS](https://www.figma.com/proto/4bobaAq9AKc1RcZjbAmJLw/lps-87872-instance-settings?node-id=138%3A5709&scaling=min-zoom&redirected=1), [NTLM](https://www.figma.com/proto/4bobaAq9AKc1RcZjbAmJLw/lps-87872-instance-settings?node-id=138%3A7162&scaling=min-zoom&redirected=1)

**Comment by drewbrokke** [comment]
Sent to Brian Lee for functional test updates: https://github.com/xbrianlee/liferay-portal/pull/277

**Pull request closed without merging**
