### PR TITLE
[TS] LPS-65498 'Unable to encrypt blank password' error on scheduled import from LDAP

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-65498

Hi Mike,

Please, see Jorge's and Norbert's discussion about blank passwords starting from [here](https://github.com/JorgeFerrer/liferay-portal/pull/737#issuecomment-218493346).

Let us know if you have concerns.

Regards,
Tibor

----
Author: @NorbertKocsis
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Hi Mike,

Can you please review this pull?

@mhan810

**Comment by lipusz** [comment]
Hi Mike,

Can you please review this pull?

@mhan810

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Mike,

Can you please proceed with this?

Thanks,
Tibor

@mhan810

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by lipusz** [comment]
Hi Mike,

Since it's a bit old, I had to talk to Norbi about this fix to get into the context again.

We think that what Jorge is struggling with is about the UserService and how we handle when the user wants to set a blank password.

What Norbi did in this fix is to ensure a/n (scheduled) import process will not fail when a blank password comes from LDAP. The commit message of @0bd7c92 also explains this: *"LPS-65498 Handle null as no password so we don't put restriction on password value outside of User service"*

Would you still like me to forward this to Jorge to double-check?

Looking forward to your thoughts.

Thanks,
Tibor

@mhan810 @NorbertKocsis

**Comment by mhan810** [comment]
k, let me look at it this morn

**Comment by mhan810** [comment]
(1) We must first determine whether we want to allow for null and blank passwords
(2) If we do not, then we will need to augment the functionality to determine whether we should sync passwords back to LDAP.

If we do not allow for null/blank passwords, then we will need to:
(1) flag for auto generation in LDAP for blank/null passwords
(2) If password is autogenerated by us, then we need to determine whether this password should be sent back to LDAP because the LDAP user could have had the password set to null/blank for a very specific reason and we probably shouldn't overwrite it.

please send back to @jorgeferrer as per his original request in https://github.com/JorgeFerrer/liferay-portal/pull/737#issuecomment-218493346

**Comment by lipusz** [comment]
Forwarded to Jorge: https://github.com/JorgeFerrer/liferay-portal/pull/760

**Pull request closed without merging**
