### PR TITLE
LPS-57161

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
There are some problems with ThreadLocal indexAllVersions at Staging process.
As a solution, (1) we remove that logic and (2) to avoid duplicated reindex (a big issue of reindexDDMStructures) we call to reindex(classname, pk) with *pk = article.getResourcePrimKey()* and new index buffering will remove duplicates

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by mhan810** [comment]
@jorgediaz-lr hey sorry i haven't had time to review this one...will do today

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by mhan810** [comment]
@jorgediaz-lr, this looks like we'll be reindexing all versions quite a bit.  I don't think we should be doign this?  Will try to ping you later

**Comment by jorgediaz-lr** [comment]
Hi @mhan810 
Now at **reindexDDMStructures** we are retrieving all versions of all JournalArticles with a given structureid.
That query retrieves all JournalArticle versions and they are reindexed.

Some throughtput issues where detected at [LPS-50579] (https://issues.liferay.com/browse/LPS-50579) because doReindex method also internally reindex all versions, so in order to avoid that issue the allVersion parameter was added, see:
 - https://github.com/brianchandotcom/liferay-portal/pull/21539

To avoid adding the parameter allVersion to doReindex, avoid the ThreadLocal and avoid that LPS-50579 issue my idea is to call **reindex(classname, pk)** with pk = article.getResourcePrimKey()
For one webcontent, all its versions have the same resource primary key, so new index buffering will remove duplicates and only one JournalArticle.reindex will be executed for each webcontent.

That method JournalArticle.reindex will reindex all versions of each webcontent, so we will have the same result

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/29350

**Pull request closed without merging**
