### PR TITLE
LPS-61410

### PR DESCRIPTION
**Pull request by ChrisKian**
I went with the format bChan was going for here: https://github.com/brianchandotcom/liferay-portal/compare/b6f652e7cb...5f39756064

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Hey Michael,

Just wanted to check with you on what the issue with this PR is.  I don't believe the failed tests have anything to do with my changes.  Please let me know if you were expecting something else, and if there is anything I can do to fix it.  Thanks

**Comment by mhan810** [comment]
Yep or on vacation. Will review when I get free moment

Sent from my mobile device.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/33945

**Pull request closed without merging**
