### PR TITLE
[TECHNICAL-SUPPORT] LPS-72769

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by mhan810** [comment]
@jonathanmccann this is wierd since the indexer request buffer is in a thread local.  There shouldn't be anyone else calling it in diff threads.  This isn't the rt fix

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by holatuwol** [comment]
@mhan810 That's only true when a thread local only lives in one thread. In Liferay, since we copy thread locals between threads when things travel over the message bus (for example, reindexing).

**Comment by holatuwol** [comment]
@jonathanmccann, just an update. @mhan810 double-checked where we copy thread locals, and I misremembered. We only copy a subset of them when we move to the message bus, and parallel render (which is disabled in 7.x) is the only thing that copies them wholesale.

https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/messaging/BaseAsyncDestination.java#L291

So, we will want to take a second look.

**Comment by jonathanmccann** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/49227

**Pull request closed without merging**
