### PR TITLE
[TS] LPS-78984 Facet count and search count are not consistent with search results when pagination is used

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-78984

Hi @mhan810,

As discussed, sending this ticket for you to review.
/cc @arboliveira

This fix introduces a new configuration option:

- **Name:** Permission Filtered Search Result Accurate Count Threshold
- **Default Value:** 100

**Configuration Description**
If a search query returns search results with a count that is within this threshold, the total count after permission filtering is guaranteed to be accurate.

**CI Test**
Currently, CI tests are not working: https://github.com/arboliveira/liferay-portal/pull/442#issuecomment-375693097

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test

**Comment by lipusz** [comment]
Hi @ericyanLr 

You may forgot to run `baseline` after your changes.

**Comment by lipusz** [comment]
ci:reopen

**Comment by mhan810** [comment]
replacing w/ https://github.com/mhan810/liferay-portal/pull/1396

**Comment by ericyanLr** [comment]
Hi @lipusz, 

Thanks for the catch, apologies for forgetting to check baseline for the portal-test-util module as well.

**Pull request closed without merging**
