### PR TITLE
LPS-73804 SSRF and RFD through WSRP ProxyServlet

### PR DESCRIPTION
**Pull request by topolik**
Hi Mike,

can you please peer-review? Not sure who else can review WSRP & security 

Didn't get any response from @mikemanyoung, I guess he's hiding :smile:

Thanks!

### CODE REVIEW

**Comment by mikemanyoung** [comment]
Hi Tomas,

I must have missed your previous message, I’ll look for it. Sorry about that. 

--
Michael Young
Liferay, Inc.

**Comment by topolik** [comment]
Hi @mhan810, sorry, this should go to ee-7.0.x first because it's SEV-1. Is it possible for you to cherry-pick the commits into EE? If you won't get to it I can do it when I return. Thanks.

/cc @lipusz

**Comment by mhan810** [comment]
No worries I can do that.  Mike Young taking a look first

**Comment by mikemanyoung** [comment]
@topolik, can you send the PR to me?

--
Michael Young
Liferay, Inc.

**Comment by lipusz** [comment]
Sent to https://github.com/mikemanyoung/liferay-portal-ee/pull/3

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
