### PR TITLE
LPS-84057 Regenerate

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [](https://issues.liferay.com/browse/).<br><br>Hey Mike, I am sending this one your way.  Our team does not deal with the different methods of login too often, so I wouldd really appreciate your opinion on this.  Thanks!<br><br>/cc @pei-jung @stsquared99 @daviddotzhang @hhuijser

### CODE REVIEW

**Comment by mhan810** [comment]
@drewbrokke @daviddotzhang why do we need to change the transactional characteristics?  Can you provide the reason why your diagnosis arrives at having to change the transactional contexts?  There appears to be only 1 transactional usage (e.g. if (!user.isPasswordEncrypted()) {...update password...}.  The bug doesn't seem to trigger that section>

**Comment by daviddotzhang** [comment]
@mhan810  this is the background in the SME request ticket, https://issues.liferay.com/browse/LPP-30948?focusedCommentId=1461820&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1461820

**Comment by holatuwol** [comment]
Scanning through the code within the authenticate method, there are two UserPersistence.update calls that aren't delegating to another service method in order to perform the update.

* An unencrypted user password triggers a user update. https://github.com/liferay/liferay-portal/blob/7.1.0-ga1/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L5893-L5898
* First user login with a new password has a blank digest and triggers a user update. https://github.com/liferay/liferay-portal/blob/7.1.0-ga1/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L5943-L5957

I think it's the latter case, since the replication steps involve a new user, but it's been awhile since I debugged it.

The user update triggers model listeners, which use a transaction commit callback in order to allow LDAP updates to (1) not block the commit to the database in case those LDAP updates take a long time to complete (see [LPS-71933](https://issues.liferay.com/browse/LPS-71933)), and (2) only trigger when the transaction commits so that we don't export to LDAP. This code only runs when we're not configured to use the LDAP password policy, which should cause the transaction to rollback (see [LPS-74160](https://issues.liferay.com/browse/LPS-74160)).

**Comment by mhan810** [comment]
@holatuwol hey man traveling this week but will review tonight.

**Comment by mhan810** [comment]
@shuyangzhou see above.  I took a look at the changes from LPS-70735 in moving from @REQUIRED to @SUPPORTS for the authenticate methods.  There are scenarios where we may be updating the database w/o a transaction.  Do you recall what the concurrency impacts looked like going form @REQUIRED to @SUPPORTS?

**Comment by shuyangzhou** [comment]
@mhan810 The change in LPS-70735 was on purpose. At least in the normal login process, the only possible write operation we have is for user and it happens exactly once. There is no other write operation, therefore auto commit is good enough, we don't need to glue multiple actions into one transaction.

I did not know that LDAP is performed via a model listener. But I am not sure why this is leading to a javax.naming.NoPermissionException. The worst case is, we add another tx layer for the LDAP model listener, after all he is the one who really needs a tx. Or we keep things simple by switching userPersistence.update(user) to userLocalService.update(user). But before making a decision, I need to understand how do we get that NoPermissionException.

@holatuwol I tried to download the VM mentioned on the ticket, but I can not login the ftp with the posted username and password. Do I have to use that VM? Can you send me an instruction to reproduce it on clean master? Either way, please send the pull to me, I will take care of it.

**Comment by shuyangzhou** [comment]
Talked to @mhan810 . We are going to stay with this simple revert for now, and clean up the tx model around authenticate pipeline later.
See https://github.com/brianchandotcom/liferay-portal/pull/62000

**Comment by drewbrokke** [comment]
Closing based on the discussion above.  Thanks all.

**Pull request closed without merging**
