### PR TITLE
[TS] LPS-71456 If you configure Liferay with LDAP and the Portrait field is not mapped, after signing in the user's portrait is removed

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-71456
Caused by https://issues.liferay.com/browse/LPS-69503

Author: @ugurcancetin
Reviewers: @lipusz

Please prioritize as it affects Grow also.

Cheers,
Tibor

### CODE REVIEW

**Comment by mhan810** [comment]
go ahead and push it to bchan

**Comment by lipusz** [comment]
Thank you for the prompt reply! @mhan810

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/48010

**Pull request closed without merging**
