### PR TITLE
LPS-69521 Configurations scoped per instance cannot be modified by config files after they have been saved via the UI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69521](https://issues.liferay.com/browse/LPS-69521).<br><br>Forwarded from https://github.com/drewbrokke/liferay-portal/pull/260<br><br>/cc @jonathanmccann @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by mhan810** [comment]
@drewbrokke can you forward this one to @shuyangzhou?  This impacts file installer.

@jonathanmccann did you open an issue with Felix already?

@migue, @rotty3000 FYI

**Comment by mhan810** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/3549

**Comment by shuyangzhou** [comment]
@drewbrokke please come to talk to me tomorrow, let's see whether we can find a way without patching. Patch is generally the last resort we use, as it is hard to maintain when doing upgrade.

**Comment by mhan810** [comment]
Should pull McCann

Sent from my mobile device.

**Comment by shuyangzhou** [comment]
Right @jonathanmccann please come to find me tomorrow, sorry, I was on my phone, did not see the commits history.

**Pull request closed without merging**
