### PR TITLE
LPS-57885 DDMFields type text created as Indexable-Text are indexed as Keyword

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
@mhan810 Hi Mike,

I have reviewed your modifications and rebased some changes that have been introduced recently.
I kept the term to be searched between quotes for both types of indexations and I have made a little change in the implementation of ElasticSearch to be equivalent to the behaviour of the Solr implementation (MatchQueryTranslatorImpl).

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
ci:retest

**Comment by mhan810** [comment]
will review this wk @dacousalr sorry have been in customer meetings

**Comment by dacousalr** [comment]
Don't worry @mhan810. Thanks

**Comment by dacousalr** [comment]
ci:retest

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/30734

**Pull request closed without merging**
