### PR TITLE
[TECHNICAL-SUPPORT] LPS-62172 If importUserPasswordEnabled the password in portal will be updated to whatever the user enters on login

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-62172

/cc @NorbertKocsis

### CODE REVIEW

**Comment by lipusz** [comment]
Rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by mhan810** [comment]
@lipusz @NorbertKocsis hey guys, can you confirm what happens if we set the user's password to blank?  I think this would break the scenario where LDAPAuth is not required and we have users in the Liferay database.  For instance, I have test@liferay.com only in the LR DB, I enabled LDAPAuth and set LDAPAuth to not be required.  I think this change would prevent me from ever logging in as test again.


@holatuwol, @jonathanmccann guys, whe nyou added LPS-57942 you created this regression.  Was the intent to simply ensure that we import the user's status?  I really don't think we should be importing the entire user when they are not authenticated against LDAP.

**Comment by NorbertKocsis** [comment]
Hi,

1. The users password will never be set to blank. If you pass StringPool.BLANK there it will be autogenerated or default, based on your settings.
2. If the user doesn't exist in LDAP then he won't be imported -> nothing happens to the password

Br,
Norbert

**Comment by lipusz** [comment]
Hi @mhan810 

Please, make sure you read Norbert's reply above. Let me know if I should re-send this or you'll handle it on this pull.

Thanks,
Tibor

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/35920

**Pull request closed without merging**
