### PR TITLE
[TECHNICAL-SUPPORT] LPS-78276

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by mhan810** [comment]
@jonathanmccann this looks like a duplicate of https://github.com/mhan810/liferay-portal/pull/1393?  I asked Hugo to push to Brian but not sure if he did.

**Comment by jonathanmccann** [comment]
Sure looks like it. Guess the reporter accidentally opened the LPS twice. I'll close this one out as a duplicate, thanks.

**Pull request closed without merging**
