### PR TITLE
LPS-60044

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
hey @mhan810 do we need the portal-settings dir in resources? This is all that will ever go in it right? If so, can you remove the dir.

If more things will be added, can you resend and rename portal-settings to portal_settings

If portal-settings will be removed, can you also rename the PortlaSettings*Action.java (the web actions) and remove that prefix too.

Thx!

**Comment by JorgeFerrer** [comment]
Hey @mhan810 ,

This is technically very nice (and I think we should reuse it in other places), but I think we are complicating a lot Portal Settings. It is supposed to be a form, but now we are adding more interactions which will create a lot of usability issues. I know that was already the case for 6.2 (unfortunately, I wished I had noticed earlier), but now we are creating a framework to allow complicating the form more than it should be possible.

I think that we should either create a portlet specific for setting up LDAP servers or alternatively allow for this type of extensions points in the Config Admin portlet (this is my favorite option).

Thoughts?

**Comment by mhan810** [comment]
Sure but real question: do we have time?

**Comment by JorgeFerrer** [comment]
I don't really think that doing it right will take more time than trying to make it fit in Portal Settings. Because it really doesn't fit and will keep causing problems that will be a waste of time.

**Comment by mhan810** [comment]
Only problem: portal settings is already done.  This is the last pr

Sent from my mobile device.

**Comment by mhan810** [comment]
@JorgeFerrer I'm going to go ahead and push this in so we at least have same matching functionality to 6.2.  If we can get rewrite done in time, then the UI can be ripped out.  The backend is going to remain the same regardless.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/31885

**Comment by JorgeFerrer** [comment]
:+1: If we have time we can revisit this later

**Pull request closed without merging**
