### PR TITLE
DDMFields type text created as Indexable-Text are indexed as Keyword

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
Some considerations to this PR:

1) As it was recommended in https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/16135494, indexable-text fields begin with ddm__text and indexable-keyword fields begin with ddm__keyword.
2) Finally, it was enough to add a mapping only for ddm__keyword case to configure it for the keyword analyzer. ddm__text fields are matched by the existing locale regular expressions *_ar, *_es_ES, *_en_US, etc picking up its correspondent language analyzer.
3) In JournalArticleIndexer there is a distinction between the code for ElasticSearch and the code for Solr because Elasticsearch accepts the string value as is but Solr and Lucene need to receive it between quotes in order to work in the same way, especially if the string value contains spaces.

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
ci:retest

**Comment by mhan810** [comment]
will be reviewing today

**Comment by dacousalr** [comment]
@mhan810 Hi,

Have you had a chance to take a look at this?
Due to support reasons we would need a status update.

Thanks in advance

**Comment by mhan810** [comment]
Hey Daniel, this is on right track but I haven't had time to finish review
will try to do so today

**Comment by mhan810** [comment]
@dacousalr hey I wanted to get some more clarity on why you had to explicitly check for ES.  I'm leaving for vacation for a week so won't be able to finish this.  If this is absolutely pressing, perhaps send the response to my question and the pr to @arboliveira.  You should copy me as well.

**Comment by mhan810** [comment]
@dacousalr please see https://github.com/dacousalr/liferay-portal/pull/1.  I removed the explicit logic checking the search engine adapter.  I think we handle this already in the FieldQueryFactoryImpl.

**Pull request closed without merging**
