### PR TITLE
[TS] LPS-85702 IndexerPostProcessor not registered after restart

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-85702

Hi Mike,

@istvansajtos will add a test for this soon.

Regards,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by mhan810** [comment]
@lipusz can you confirm if these failures are related?

**Comment by lipusz** [comment]
Hi Mike,

I can't think of any way how the IndexerPostProcessor registration can be related to ES remote clustering and to searching with different scopes.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
All passed today. :+1:

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/63893

**Pull request closed without merging**
