### PR TITLE
LPS-54335 Additional index settings from contributors and configurations

### PR DESCRIPTION
**Pull request by arboliveira**
We'll need a different story for additional/replacement mappings. The Elasticsearch API for mappings is not additive like its API for settings, it can only be invoked once per index. We will need to tamper with the mappings JSON in order to inject any additional settings before invoking the API.

cc @gallindo

### CODE REVIEW

**Comment by mhan810** [comment]
Hey guys, should we split up the ElasticsearchConfiguration object?  Looking at the CompanyIndexFactory, the current code is going to force an index mapping change each time the ElasticsearchConfiguration object gets changed.  This can lead to a lot of "fake" changes?

**Comment by mhan810** [comment]
Also:
protected void addIndexSettingsContributor(
		IndexSettingsContributor indexSettingsContributor) {

This may not have the proper effect?  What if I add an index settings contributor after the component has already activated?  This is not a required reference and thus could be called after the activate method?

**Comment by arboliveira** [comment]
+1 for spawning an `ElasticsearchIndexConfiguration` class. Although the `activate` method is harmless by now (just repopulates private fields) it's always better to avoid unrelated spurious triggers. Also, when we add the upcoming configs for custom mappings (and other index stuff ES offers like aliases) it's nice we already have a dedicated config for them instead of cluttering the main one.

About the settings contributors: it's fine to have `addIndexSettingsContributor` called after the `activate` method - they just repopulate private fields - as long as *both* of them are finished *before* `createIndices` kicks in; that's where all the real action is. I do believe though we should add "(requires reindex)" to the `description` of all configs in the new `ElasticsearchIndexConfiguration`, as well as making it clear in documentation that deploying any plugin providing an `IndexSettingsContributor` will require a full reindex for the index to be recreated including the new contributed settings.

**Comment by mhan810** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/30431

**Comment by mhan810** [comment]
For now keeping a single ESConfig

**Pull request closed without merging**
