### PR TITLE
LPS-60502 Add search box in the UI

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Here are the UI changes to add search to System Settings

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@mhan810 We should get this in this week so that it makes it to the beta. Is it doable?

**Comment by mhan810** [comment]
This wk prob tough since I have a rfp to finish reviewing and prep for my
offsite next wk.  By mid Dec should be OK.

**Comment by JorgeFerrer** [comment]
Argh, mid dec? How about next week?

I'm ok with an initial impl that I can finish.

**Comment by mhan810** [comment]
I'll see what I can do and squeeze in a few hrs here and there

**Comment by JorgeFerrer** [comment]
Hey Mike,

Have you had a chance to work on this? Should we decide to drop it from 7.0?

**Comment by mhan810** [comment]
Not yet, been going writing docs for training this week.  Will try later
this week.



If you want to drop it for now and add it in if I get thru that’s fine too



*From:* Jorge Ferrer [mailto:notifications@github.com]
*Sent:* Wednesday, December 9, 2015 2:37 AM
*To:* mhan810/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] LPS-60502 Add search box in the UI (#825)



Hey Mike,

Have you had a chance to work on this? Should we decide to drop it from 7.0?

—
Reply to this email directly or view it on GitHub
<https://github.com/mhan810/liferay-portal/pull/825#issuecomment-163150467>.

**Comment by mhan810** [comment]
https://github.com/JorgeFerrer/liferay-portal/pull/624

**Pull request closed without merging**
