### PR TITLE
LPS-60414

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
@mhan810 
could you kindly have a look at it ?

**Comment by mhan810** [comment]
It's a holiday next few days.  Will look once I get a chance

**Comment by mhan810** [comment]
Actually can you forward to Andre do Oliveira?

**Comment by hhuijser** [comment]
Sent to Andre: https://github.com/arboliveira/liferay-portal/pull/72

**Pull request closed without merging**
